[package]
name = "Auxide_Comp"
version = "0.1.0"
authors = ["fishp0cket <77080489+fishp0cket@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
